<?php

/* *****************************************************************
 *  Copyright notice
 *
 *  (c) 2012 Anno v. Heimburg <avonheimburg@agenturwerft.de>, Agenturwerft
 *
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 * **************************************************************** */

namespace T3b\T3bCommon\ViewHelpers;
/**
 * A ViewHelper that wraps its contents in a link generated by typolink
 *
 * Arguments:
 *  parameter: TypoLink-Parameter, required
 *  target, class, title: will be written into the a-tag as specified
 */
class TypolinkViewHelper extends BaseViewHelper
{

    public function initializeArguments() {
        $this->registerArgument('parameter', 'string', 'Parameter for typolink', TRUE);
        $this->registerArgument('class', 'string', 'CSS Classes', FALSE, '');
        $this->registerArgument('target', 'string', 'Link target', FALSE, '');
        $this->registerArgument('title', 'string', 'Link title', FALSE, '');
    }

    public function render() {
        $content = $this->renderChildren();

        $typolinkConfig = array();
        $typolinkConfig['parameter'] = $this->arguments['parameter'];

        if ($this->arguments['title']) {
            $typolinkConfig['title'] = $this->arguments['title'];
        }

        // a tag params
        $aTagParams = array();

        if ($this->arguments['class']) {
            $aTagParams[] = 'class="' . $this->arguments['class'] . '"';
        }

        if ($this->arguments['target']) {
            $aTagParams[] = 'target="' . $this->arguments['target'] . '"';
        }

        if (! empty($aTagParams)) {
            $typolinkConfig['ATagParams'] = implode(' ', $aTagParams);
        }


        $html = $this->cObject->typoLink($content, $typolinkConfig);

        return $html;
    }

}

?>
