<?php

/* *****************************************************************
 *  Copyright notice
 *
 *  (c) 2012 Anno v. Heimburg <avonheimburg@agenturwerft.de>, Agenturwerft
 *
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 * **************************************************************** */

namespace T3b\T3bCommon\ViewHelpers;
/**
 * A ViewHelper that wraps its contents in a link generated by typolink
 *
 * Arguments:
 *  parameter: TypoLink-Parameter, required
 *  target, class, title: will be written into the a-tag as specified
 */
class TypoLinkViewHelper extends BaseViewHelper
{

    /**
     * Wrap content in link using typolink
     *
     * @param string $parameter Parameter for typolink
     * @param string $class CSS Classes
     * @param string $target Link target
     * @param string $title Link title
     * @return string Linked content
     */
    public function render($parameter, $class = '', $target = '', $title = '') {
        $content = $this->renderChildren();

        $typoLinkConfig = array();
        $typoLinkConfig['parameter'] = $parameter;

        if ($title) {
            $typoLinkConfig['title'] = $title;
        }

        // a tag params
        $aTagParams = array();

        if ($class) {
            $aTagParams[] = 'class="' . $class . '"';
        }

        if ($target) {
            $aTagParams[] = 'target="' . $target . '"';
        }

        if (! empty($aTagParams)) {
            $typoLinkConfig['ATagParams'] = implode(' ', $aTagParams);
        }


        $html = $this->cObject->typoLink($content, $typoLinkConfig);

        return $html;
    }

}

?>
